// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// update_otrend_
void update_otrend_(double& x, double& value, double& n, double& nn, double& x_sum, double& n_sum, double& xn_sum, double& nn_sum, double& det);
RcppExport SEXP _autotrade_update_otrend_(SEXP xSEXP, SEXP valueSEXP, SEXP nSEXP, SEXP nnSEXP, SEXP x_sumSEXP, SEXP n_sumSEXP, SEXP xn_sumSEXP, SEXP nn_sumSEXP, SEXP detSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double& >::type value(valueSEXP);
    Rcpp::traits::input_parameter< double& >::type n(nSEXP);
    Rcpp::traits::input_parameter< double& >::type nn(nnSEXP);
    Rcpp::traits::input_parameter< double& >::type x_sum(x_sumSEXP);
    Rcpp::traits::input_parameter< double& >::type n_sum(n_sumSEXP);
    Rcpp::traits::input_parameter< double& >::type xn_sum(xn_sumSEXP);
    Rcpp::traits::input_parameter< double& >::type nn_sum(nn_sumSEXP);
    Rcpp::traits::input_parameter< double& >::type det(detSEXP);
    update_otrend_(x, value, n, nn, x_sum, n_sum, xn_sum, nn_sum, det);
    return R_NilValue;
END_RCPP
}
// otrend_
Rcpp::NumericVector otrend_(std::vector<double> x);
RcppExport SEXP _autotrade_otrend_(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(otrend_(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_autotrade_update_otrend_", (DL_FUNC) &_autotrade_update_otrend_, 9},
    {"_autotrade_otrend_", (DL_FUNC) &_autotrade_otrend_, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_autotrade(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
