# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_otrend_ <- function(x, value, n, nn, x_sum, n_sum, xn_sum, nn_sum, det) {
    invisible(.Call(`_autotrade_update_otrend_`, x, value, n, nn, x_sum, n_sum, xn_sum, nn_sum, det))
}

otrend_ <- function(x) {
    .Call(`_autotrade_otrend_`, x)
}

